export const CHANGE_TAB = 'CHANGE_TAB';
export const CHANGE_DEP_DATE = 'CHANGE_DEP_DATE';
export const CHANGE_RET_DATE = 'CHANGE_RET_DATE';
export const CHANGE_PRICE_RANGE = 'CHANGE_PRICE_RANGE';
export const SET_FLIGHT_RESULT = 'SET_FLIGHT_RESULT';
